XX
XXXXXXXXXXXXX
XXX XXXXXX XXXXXX
XXXXXXXX XXX
XX

XXX
 X XXXXXX XX XX XXXXX XX XXXXXXXXX XX XXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX
 X
 X XXXXX XXXX XXXX XXX XXXX XXXXXXXXX XXX XXXXXXXXXXX XXXXXX XXXX XX XXXXXXXXX
 X XXXXXXXX XXXXXXX XXXXXXXX XXX XXXXXXXXX
 X
 X XXXXXXX XXXX XXXXXXXXXX
 X
 X XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXX XXXX XXXXXXXX
 X XXXXXXX XXXXXXXXX XXXX XX XXX XXXXX XX XXXXXXXXXX
 X XXXXXXXXX
 X XXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXX XXXXXX X XXX
 XX

XXX XXXXXXXX XXXXX XXXXXXX
 X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 X
 X XXXXXXXXX XXX XXXXXXXXX XXXX XXX XXX XXXXXXXXXXX
 X
 X XXXX XXXXXX XXXX XX XXXXXXXX XXXXX XXX XXX XXXXXXX XXXXX XX XXX
 X XXXXXXX XXXX XX XXX XXXX XXXXXXXXX XX XXXX XXXXXX XXXXX
 XX

XXX XXXXXXXX XXXXX XXXXXXX
 X XXXXXXXXXXXXXXXXXXXXXXXX
 X
 X XXXXXXXXX XXX XXXXXXXXX XXXX XXX XXX XXXXXXXXXXX
 X
 X XXXX XXXXXX XXXX XX XXXXXXXX XXXXX XXX XXX XXXXXXX XXXXX XX XXX
 X XXXXXXX XXXX XX XXX XXXX XXXXXXXXX XX XXXX XXXXXX XXXXX
 XX

XXX XXXXXXXX XXXXX XXXXXXXX
 X XXXXXXXXXXXXXXXXXXXXXXX
 X
 X XXXXXXXXX XXX XXXXXXXXX XXXX XXX XXX XXXXXXXXXXX
 X
 X XXXX XXXXXX XXXX XX XXXXXXXX XXXXX XXX XXX XXXXXXX XXXXX XX XXX
 X XXXXXXX XXXX XX XXX XXXX XXXXXXXXX XX XXXX XXXXXX XXXXX
 XX

XXX XXXXXXXX XXXXX XXXXXXX
 X XXXXXXXXXXXXXXXXXXXXXXXX
 X
 X XXXXXXXXX XXX XXXXXXXXX XXXX XXX XXX XXXXXXXXXXX
 X
 X XXXX XXXXXX XXXX XX XXXXXXXX XXXXX XXX XXX XXXXXXX XXXXX XX XXX
 X XXXXXXX XXXX XX XXX XXXX XXXXXXXXX XX XXXX XXXXXX XXXXX
 XX

XXX XXXXXXXX XXXXX XXXXXXX
 X XXXXXXXXXXXXXXXXXXXX
 X
 X XXXXXXXXX XXX XXXXXXXXX XXXX XXX XXX XXXXXXXXXXX
 X
 X XXXX XXXXXX XXXX XX XXXXXXXX XXXXX XXX XXX XXXXXXX XXXXX XX XXX
 X XXXXXXX XXXX XX XXX XXXX XXXXXXXXX XX XXXX XXXXXX XXXXX
 XX
